### PR TITLE
Fixed typos in LYWSD03MMC converter 2.0

### PR DESCRIPTION
**Pull request by maaad**
Sry, previous pr was broken

### CODE REVIEW

**Comment by pvvx** [comment]
It works?
I don't use Z2M. ZHA does not require any converters...

**Comment by maaad** [comment]
Yes, it work's with LYWSD03MMC-z.

**Comment by pvvx** [comment]
"[index.json](https://github.com/pvvx/ZigbeeTLc/blob/master/bin/index.json)" is required in Z2M ?

**Comment by maaad** [comment]
Yes, it works if you define it in zigbee_ota_override_index_location.
BTW, it should merged it in [global Zigbee-OTA index](https://github.com/Koenkk/zigbee-OTA/blob/master/index.json)

**Comment by robvanoostenrijk** [comment]
@maaad, I can see you changed the min and max value definitions away from the values provided in the ZigbeeTLc documentation: 

https://github.com/pvvx/ZigbeeTLc/

Supported values are -372.67..327.67, but its changed to -50..50.

@pvvx,
I guess the question here is to support what is technically exposed or rather what makes sense to the user?

**Comment by pvvx** [comment]
I don't know if the graphics scale is scalable in Z2M or not.
So I limited the script to values that make sense.

**Comment by maaad** [comment]
> @maaad, I can see you changed the min and max value definitions away from the values provided in the ZigbeeTLc documentation:
> 
> https://github.com/pvvx/ZigbeeTLc/
> 
> Supported values are -372.67..327.67, but its changed to -50..50.
> 
I didn't change it (https://github.com/pvvx/ZigbeeTLc/commit/576ee036c757865389ff2ac068dca61254dbf9be)
BTW, https://github.com/devbis/z03mmc/blob/master/converters/lywsd03mmc.js uses -100..100

**Pull request merged**
